/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Tenant;
import manager.ApartmentManager;
import model.Payment;
import model.LatePayment;
import model.OnTimePayment;


/**
 *
 * @author integ
 */
public class PaymentScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentScreen.class.getName());

    /**
     * Creates new form PaymentScreen
     */
    private ApartmentManager manager;
    private MainMenu mainMenu;
    DefaultTableModel dtm;
    DefaultListModel dlm;
    
    public PaymentScreen(ApartmentManager manager, MainMenu mainMenu) {
        initComponents();
        setTitle("Payment");
        this.manager = manager;
        this.mainMenu = mainMenu;
        
        //setting table
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Amount", "Date"});
        paymentTable.setModel(dtm);
        
        // setting list
        dlm= new DefaultListModel();
        paidList.setModel(dlm);
        
        // bulunan tüm kiracıları combboxa ekleme
        for (Tenant t : manager.getTenants()) {
            cmbxTenant.addItem(t.getName());
        }
        
        cmbxTenant.setSelectedItem(null);
        lblName.setText(null);
        lblApt.setText("");
        lblRent.setText(null);
        
        // month ve year cmbxlarını dolurma
        int[] months = {1,2,3,4,5,6,7,8,9,10,11,12};
        for(int m : months) cmbxMonth.addItem(m+"");
        
        for(int i=2026;i<=2050;i++){
            cmbxYear.addItem(i+"");
        }
        
        //payment type combobox doldurma 
        cmbxPaymentType.addItem("On Time");
        cmbxPaymentType.addItem("Late");
        
        //Jlist update 
        updatePaidList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbxTenant = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        btnPay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblApt = new javax.swing.JLabel();
        lblRent = new javax.swing.JLabel();
        cmbxMonth = new javax.swing.JComboBox<>();
        cmbxYear = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbxPaymentType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paidList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbxTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTenantActionPerformed(evt);
            }
        });

        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        jLabel1.setText("Amount:");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name:");

        jLabel3.setText("Apartment: ");

        jLabel4.setText("Rent:");

        lblRent.setText("90000");

        jLabel5.setText("Date:");

        cmbxPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxPaymentTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Payment Type:");

        jScrollPane2.setViewportView(paidList);

        jLabel7.setText("Paid Tenants:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(718, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbxTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(lblApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblName)
                    .addComponent(cmbxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblApt))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblRent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        try{
            int i=cmbxTenant.getSelectedIndex();
            //selection control
            if(i==-1){
               JOptionPane.showMessageDialog(this, "Select a tenant!");
               return;
            }
            Tenant t = manager.getTenants().get(i);

            double amount = Double.parseDouble(txtAmount.getText());
        
            //complex rule: payment amount must be >0
            if(amount <=0){
                JOptionPane.showMessageDialog(this, "Invalid payment amount!");
                return ;
            }
            //COMPLEX RULE: payment can not be more then debt amount if the payment is on time otherwise you can because there is an delaying extra
            // but in both cases payment before extras cannot be more than rent
            int month = Integer.parseInt(cmbxMonth.getSelectedItem().toString());
            int year = Integer.parseInt(cmbxYear.getSelectedItem().toString());

            double paidThisMonth = manager.getMonthlyPaid(t.getAptNo(), month, year);
            double debt = t.getRent() - paidThisMonth;
            
            if(amount > debt){
                JOptionPane.showMessageDialog(this, "You cannot pay more than debt!");//
                txtAmount.setText("");
                return;
            }
            if(amount>t.getRent()){
                JOptionPane.showMessageDialog(this, "You cannot pay more than monthly rent!");
                txtAmount.setText("");
                return;
            }
            
            
            //Complex rule: you cannot pay more rent more than once a year
            if(manager.hasPayment(t.getAptNo(), month, year)&& manager.getMonthlyPaid(t.getAptNo(), month, year)==t.getRent()){
                JOptionPane.showMessageDialog(this, "Payment already exists for this month!");
                return;
            }
            
            //paymentType set
            String type = cmbxPaymentType.getSelectedItem().toString();
            
        
            //payment ekleme 
            Payment p;
            if(type.equals("Late")){
                JOptionPane.showMessageDialog(this, "%2 extra amount will applied for delays!");
                p=new LatePayment(t.getAptNo(), amount, month, year, 5);
            }else{
                p=new OnTimePayment(t.getAptNo(), amount, month, year);
            }
            manager.addPayment(p);
        
            txtAmount.setText("");
            
            //jlist update etme
            updatePaidList();

            //sadece seçili tenantın tablosunu yenile
            dtm.setRowCount(0); // tabloyu temizle
            
            for (Payment payment : manager.getPayments()) {
                if (payment.getAptNo() == t.getAptNo()) {
                    dtm.addRow(new Object[]{
                        payment.calculateAmount(),
                        payment.getMonth()+"/"+payment.getYear()
                    });
                }
            }
        
            JOptionPane.showMessageDialog(this, "Payment added!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid Input!");
        }
        
    }//GEN-LAST:event_btnPayActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // geri butonu
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void cmbxTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTenantActionPerformed
        // TODO add your handling code here:
        int i = cmbxTenant.getSelectedIndex();
        
        if(i == -1)return;
        
        Tenant t = manager.getTenants().get(i);
        
        lblName.setText(t.getName());
        lblApt.setText(t.getAptNo()+"");
        lblRent.setText(t.getRent()+"");
        
        //loading payments for spesific tenant
            dtm.setRowCount(0); // tabloyu temizle

            for (Payment p : manager.getPayments()) {
                if (p.getAptNo() == t.getAptNo()) {
                    dtm.addRow(new Object[]{
                        p.calculateAmount(),
                        p.getMonth()+"/"+p.getYear(),
                    });
                }
            }
    }//GEN-LAST:event_cmbxTenantActionPerformed

    private void cmbxPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxPaymentTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    // jlistte güncellemeleri yapmak için
    private void updatePaidList() {
    dlm.clear(); // Listeyi her seferinde sıfırla ki isimler mükerrer olmasın
    for (Tenant t : manager.getTenants()) {
        // manager içindeki borç hesaplama fonksiyonunu kullanıyoruz
        if (manager.calculateDebt(t) <= 0) { 
            dlm.addElement(t.getName() + " - (Paid)");
        }
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cmbxMonth;
    private javax.swing.JComboBox<String> cmbxPaymentType;
    private javax.swing.JComboBox<String> cmbxTenant;
    private javax.swing.JComboBox<String> cmbxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApt;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRent;
    private javax.swing.JList<String> paidList;
    private javax.swing.JTable paymentTable;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
}
