/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import model.Payment;
import model.Tenant;
import manager.ApartmentManager;

/**
 *
 * @author integ
 */
public class ReportScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportScreen.class.getName());

    /**
     * Creates new form ReportScreen
     */
     private ApartmentManager manager;
    private MainMenu mainMenu;
    
    DefaultTableModel dtm;
    
    //constructor
    public ReportScreen(ApartmentManager manager , MainMenu menu) {
        initComponents();
        setTitle("Report");
        this.mainMenu=menu;
        this.manager= manager;
        //set model
        dtm= new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Name", "Apt No", "Monthly Rent", "Total Rent(12 months)","Total Paid", "Debt"});
        jTable1.setModel(dtm);
        
        //load data and set labels for total values
        
        double totalIncome = 0;
        double totalDebt=0;
        
        for(Tenant t: manager.getTenants()){
            double totalPaid=0;
            for(Payment p: manager.getPayments()){
                if(p.getAptNo()== t.getAptNo()){
                    totalPaid += p.calculateAmount();
                }
            }
            double debt = manager.calculateDebt(t);
            
            totalIncome += totalPaid;
            
            if(debt>0){
                totalDebt += debt;
            }
            
            
            
            
        }
        
        
        // label updating
        lblTotalIncome.setText(totalIncome+"");
        lblTotalDebt.setText(totalDebt+"");
        lblTenantCount.setText(manager.getTenants().size()+"");
        
        //average label calculating
        double rentSum=0;
        int tenantsNo=0;
        for(Tenant t: manager.getTenants()){
            tenantsNo++;
            rentSum+=t.getRent();
        }
        double avgRent = rentSum/tenantsNo;
        lblAvgRent.setText(avgRent + "");
        
        //button group setting
        ButtonGroup group = new ButtonGroup();
        group.add(rdbtnAll);
        group.add(rdbtnDebtors);
        group.add(rdbtnPaid);
        
        //defaultta boş olmasın diye 
        rdbtnAll.setSelected(true); // all seçeneği en başta seçili olacak
        //defaullt filter is all
        loadTableFilters("All");
    
    }    
        
    //radio butonlarla filtreyi uygulamak
    private void loadTableFilters(String filter){
        dtm.setRowCount(0);//tabloyu sıfırlamak
        
        for(Tenant t: manager.getTenants()){
            double totalPaid =0;
            
            for(Payment p: manager.getPayments()){
                if(p.getAptNo() == t.getAptNo()){
                    totalPaid += p.calculateAmount();
                }
            }
            
            double debt = manager.calculateDebt(t);
            
            //FILTERS
            if(filter.equals("Debtors") && debt <=0)continue;
            if(filter.equals("Paid")&&debt>0)continue;
            
            dtm.addRow(new Object[]{t.getName(), t.getAptNo(), t.getRent(), (t.getRent()*12),totalPaid, ((t.getRent()*12)-totalPaid)});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalIncome = new javax.swing.JLabel();
        lblTotalDebt = new javax.swing.JLabel();
        lblTenantCount = new javax.swing.JLabel();
        rdbtnPaid = new javax.swing.JRadioButton();
        rdbtnDebtors = new javax.swing.JRadioButton();
        rdbtnAll = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        lblAvgRent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Total Income: ");

        jLabel2.setText("Total Debt:");

        jLabel3.setText("Tenant Count:");

        lblTotalIncome.setText("jLabel4");

        lblTotalDebt.setText("jLabel4");

        lblTenantCount.setText("jLabel5");

        rdbtnPaid.setText("Paid");
        rdbtnPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnPaidActionPerformed(evt);
            }
        });

        rdbtnDebtors.setText("Debtors");
        rdbtnDebtors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnDebtorsActionPerformed(evt);
            }
        });

        rdbtnAll.setText("All");
        rdbtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAllActionPerformed(evt);
            }
        });

        jLabel4.setText("Average Rent:");

        lblAvgRent.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(28, 28, 28)
                                        .addComponent(lblAvgRent, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTotalIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                            .addComponent(lblTotalDebt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTenantCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdbtnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbtnDebtors, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbtnPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 295, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rdbtnAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbtnDebtors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdbtnPaid))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblTotalIncome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblTotalDebt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTenantCount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvgRent)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void rdbtnPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnPaidActionPerformed
        // paid seçeneği
        loadTableFilters("Paid");
    }//GEN-LAST:event_rdbtnPaidActionPerformed

    private void rdbtnDebtorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnDebtorsActionPerformed
        //debtors filtresi seçeneği
        loadTableFilters("Debtors");
    }//GEN-LAST:event_rdbtnDebtorsActionPerformed

    private void rdbtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAllActionPerformed
        //all filtresi
        loadTableFilters("All");
    }//GEN-LAST:event_rdbtnAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAvgRent;
    private javax.swing.JLabel lblTenantCount;
    private javax.swing.JLabel lblTotalDebt;
    private javax.swing.JLabel lblTotalIncome;
    private javax.swing.JRadioButton rdbtnAll;
    private javax.swing.JRadioButton rdbtnDebtors;
    private javax.swing.JRadioButton rdbtnPaid;
    // End of variables declaration//GEN-END:variables
}
