/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.*;
import model.*;
import java.util.ArrayList;


/**
 *
 * @author integ
 */
public class PaymentManagement_adminFrame extends javax.swing.JFrame {
    
    private PaymentDAO paymentDAO;
    private TenantDAO tenantDAO;
    private ArrayList<Tenant> tenantList;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaymentManagement_adminFrame.class.getName());

    /**
     * Creates new form PaymentScreen
     */
    ;
    private AdminMainMenu mainMenu;
    DefaultTableModel dtm;
    
    public PaymentManagement_adminFrame(AdminMainMenu mainMenu) {
        initComponents();
        setTitle("Payment");
        
        this.mainMenu = mainMenu;
        
        paymentDAO = new PaymentDAO();
        tenantDAO = new TenantDAO();

        tenantList = tenantDAO.loadTenants(new DefaultTableModel(), mainMenu.currentadminid);

        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{
            "Payment ID",
            "Tenant ID",
            "Amount",
            "Date",
            "Type",
            "Late Days",
            "Calculated Amount"
        });
        paymentTable.setModel(dtm);

        cmbxTenant.removeAllItems();

        for (Tenant t : tenantList) {
            cmbxTenant.addItem(t.getName());
        }

        cmbxPaymentType.removeAllItems();
        cmbxPaymentType.addItem("All");
        cmbxPaymentType.addItem("On Time");
        cmbxPaymentType.addItem("Late");

        cmbxTenant.setSelectedIndex(-1);

        lblTenantName.setText("");
        lblApartmentId.setText("");
        lblRentAmount.setText("");
        lblTotalPaid.setText("");
        lblDebt.setText("");
        
    }
    
    //SEÇİLEN TENANTIN ÖDEMELERINI YÜKLER
    private void loadSelectedTenantPayments() {
        int index = cmbxTenant.getSelectedIndex();

        if (index == -1 || tenantList == null) {
            return;
        }

        Tenant tenant = tenantList.get(index);

        String filter = cmbxPaymentType.getSelectedItem().toString();

        lblTenantName.setText(tenant.getName());
        lblApartmentId.setText(String.valueOf(tenant.getAptId()));
        lblRentAmount.setText(String.valueOf(tenant.getRentAmount()));

        double totalPaid = paymentDAO.getTotalPaidByTenant(tenant.getTenantId());
        double debt = tenant.getRentAmount() - totalPaid;

        if (debt < 0) {
            debt = 0;
        }

        lblTotalPaid.setText(String.valueOf(totalPaid));
        lblDebt.setText(String.valueOf(debt));

        dtm.setRowCount(0);

        ArrayList<Payment> payments =
                paymentDAO.loadPaymentsByTenant(tenant.getTenantId(), filter);

        for (Payment p : payments) {
            dtm.addRow(new Object[]{
                p.getPaymentId(),
                p.getTenantId(),
                p.getAmount(),
                p.getPaymentDate(),
                p.getPaymentType(),
                p.getLateDays(),
                p.calculateAmount()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbxTenant = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        backbtn = new javax.swing.JButton();
        lblTenantName = new javax.swing.JLabel();
        lblApartmentId = new javax.swing.JLabel();
        lblRentAmount = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblApt = new javax.swing.JLabel();
        lblRent = new javax.swing.JLabel();
        cmbxPaymentType = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPaid = new javax.swing.JLabel();
        lblDebt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbxTenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxTenantActionPerformed(evt);
            }
        });

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(paymentTable);

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        lblTenantName.setText("Tenant Name:");

        lblApartmentId.setText("Apartment ID: ");

        lblRentAmount.setText("Rent Amount:");

        lblRent.setText("90000");

        cmbxPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxPaymentTypeActionPerformed(evt);
            }
        });

        jLabel6.setText("Filter:");

        lblTotalPaid.setText("Total Paid: ");

        lblDebt.setText("Debt:");

        jLabel2.setText("Select Tenant:");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(lblApt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbxTenant, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTenantName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRentAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblApartmentId)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblRent, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTotalPaid))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(cmbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbxTenant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblApt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTenantName)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApartmentId)
                            .addComponent(lblRent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(lblRentAmount)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalPaid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDebt)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbxPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // geri butonu
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void cmbxTenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxTenantActionPerformed
        //combobox seçiminde Tenant seçilince çalışacak kod
        loadSelectedTenantPayments();
    }//GEN-LAST:event_cmbxTenantActionPerformed

    private void cmbxPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxPaymentTypeActionPerformed
        // Filter değişince çalışacak kod
        loadSelectedTenantPayments();
    }//GEN-LAST:event_cmbxPaymentTypeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadSelectedTenantPayments();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }
    // jlistte güncellemeleri yapmak için
    private void updatePaidList() {
    /*dlm.clear(); // Listeyi her seferinde sıfırla ki isimler mükerrer olmasın
    for (Tenant t : manager.getTenants()) {
        // manager içindeki borç hesaplama fonksiyonunu kullanıyoruz
        if (manager.calculateDebt(t) <= 0) { 
            dlm.addElement(t.getName() + " - (Paid)");
        }
    }*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbxPaymentType;
    private javax.swing.JComboBox<String> cmbxTenant;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApartmentId;
    private javax.swing.JLabel lblApt;
    private javax.swing.JLabel lblDebt;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRent;
    private javax.swing.JLabel lblRentAmount;
    private javax.swing.JLabel lblTenantName;
    private javax.swing.JLabel lblTotalPaid;
    private javax.swing.JTable paymentTable;
    // End of variables declaration//GEN-END:variables
}
