/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;
import model.*;
import DAO.*;
import javax.swing.JOptionPane;
import service.FileReportService;

/**
 *
 * @author integ
 */
public class ReportManagement_adminFrame extends javax.swing.JFrame {
    private AdminMainMenu mainMenu;
    private User currentUser;
    private int currentAdminId;
    private FileReportService reportService;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReportManagement_adminFrame.class.getName());

    /**
     * Creates new form ReportScreen
     */
    
    DefaultTableModel dtm;
    
    //constructor
    public ReportManagement_adminFrame(AdminMainMenu mainMenu, User user) {
        initComponents();
        setTitle("Report");
        this.mainMenu = mainMenu;
        this.currentUser = user;
        this.currentAdminId = user.getId();

        reportService = new FileReportService();

        String report = reportService.generateReport(currentAdminId);
        txtReportArea.setText(report);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        btnExportText = new javax.swing.JButton();
        btnSaveBinary = new javax.swing.JButton();
        btnReadBinary = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReportArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnExportText.setText("Export Text Report");
        btnExportText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportTextActionPerformed(evt);
            }
        });

        btnSaveBinary.setText("Save Binary Backup");
        btnSaveBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBinaryActionPerformed(evt);
            }
        });

        btnReadBinary.setText("Read Binary Backup");
        btnReadBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadBinaryActionPerformed(evt);
            }
        });

        txtReportArea.setColumns(20);
        txtReportArea.setRows(5);
        jScrollPane2.setViewportView(txtReportArea);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REPORT & FILE OPERATIONS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnExportText, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSaveBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnReadBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportText, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReadBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnExportTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportTextActionPerformed
        // TODO add your handling code here:
        String report = reportService.generateReport(currentAdminId);
        txtReportArea.setText(report);

        reportService.writeTextReport(report);

        JOptionPane.showMessageDialog(this, "Text report exported successfully!");
    }//GEN-LAST:event_btnExportTextActionPerformed

    private void btnSaveBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBinaryActionPerformed
        // TODO add your handling code here:
        String report = reportService.generateReport(currentAdminId);
        txtReportArea.setText(report);

        reportService.writeBinaryReport(report);

        JOptionPane.showMessageDialog(this, "Binary backup saved successfully!");
    }//GEN-LAST:event_btnSaveBinaryActionPerformed

    private void btnReadBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadBinaryActionPerformed
        // TODO add your handling code here:
        String report = reportService.readBinaryReport();
        txtReportArea.setText(report);
    }//GEN-LAST:event_btnReadBinaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnExportText;
    private javax.swing.JButton btnReadBinary;
    private javax.swing.JButton btnSaveBinary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtReportArea;
    // End of variables declaration//GEN-END:variables
}
