/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author integ
 */

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import manager.ApartmentManager;
import model.Tenant;
public class TenantScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TenantScreen.class.getName());

    /**
     * Creates new form TenantScreen
     */
    
    private ApartmentManager manager;
    private MainMenu mainMenu;
    
    DefaultTableModel dtm;
    
    public TenantScreen(ApartmentManager manager, MainMenu mainMenu) {
        initComponents();
        setTitle("Tenant");
        this.manager =manager;
        this.mainMenu = mainMenu;
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new Object[]{"Name", "Apartment No", "Rent"});
        jTable1.setModel(dtm);
        
        
        
        for (Tenant t : manager.getTenants()) {
            dtm.addRow(new Object[]{
            t.getName(),
            t.getAptNo(),
            t.getRent()
        });
}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtAptNo = new javax.swing.JTextField();
        txtRent = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Apartment No:");

        jLabel3.setText("Rent:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(40, 40, 40))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(81, 81, 81)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(92, 92, 92)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAptNo, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(txtName)
                            .addComponent(txtRent))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete)
                            .addComponent(btnUpdate)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        mainMenu.setVisible(true); // geri mainmenuye döner 
        this.dispose(); // bu ekranı kapatır(tanant ekranı)
    }//GEN-LAST:event_backbtnActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try{
            String name = txtName.getText();
            int aptNo= Integer.parseInt(txtAptNo.getText());
            double rent = Double.parseDouble(txtRent.getText());
            
            //complex rule: aynı daire farklı kiracı olmaz kontrolu
            for(Tenant t: manager.getTenants()){
                if(t.getAptNo() == aptNo){
                    JOptionPane.showMessageDialog(this,"This apartment is not suitable for rent!" );
                    
                    txtAptNo.setText("");
                    
                    return;
                }
            }
            
            //kiracı oluşturma
            Tenant t = new Tenant(name,aptNo,rent);
            //managera ekleme
            manager.addTenant(t);

            //tabloya aktarma
            dtm.addRow(new Object[]{name, aptNo, rent});
            
            txtName.setText("");
            txtAptNo.setText("");
            txtRent.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Invalid input!" );
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        //JTable → seç → seçim kontrol → are you sure → yes-delete → no-return
        int selectedRow= jTable1.getSelectedRow();
        
        if(selectedRow == -1){ //seçim yapıldı mı kontrolu
            JOptionPane.showMessageDialog(this, "Please select a tenant!");
            return;
        }
        //borç kontrolu 
        Tenant t = manager.getTenants().get(selectedRow);
        double debt = manager.calculateDebt(t);
        
        if(debt > 0){
            JOptionPane.showMessageDialog(this, "This tenant has debt! cannot delete.");
            return;
        }
        
        //sure test
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Delete", JOptionPane.YES_NO_OPTION);
        
        if(confirm == JOptionPane.NO_OPTION){
            return;
        }
        
        //Arraylistten silme 
        manager.getTenants().remove(selectedRow);
        //tablodan silme
        dtm.removeRow(selectedRow);
        
        //textFieldler dolunca silmek için
        txtName.setText("");
        txtAptNo.setText("");
        txtRent.setText("");
        
        //confirming
        JOptionPane.showMessageDialog(this, "Tenant deleted!");
        
        //tablodan seçilen satırı temizler
        jTable1.clearSelection();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //JTable → seç → bilgileri inputlara doldur → değiştir → update et
        int selectedRow = jTable1.getSelectedRow();
        
        //seçim yapıldı mı kontrolu
        if(selectedRow == -1){ 
            JOptionPane.showMessageDialog(this, "Please select a tenant!");
            return;
        }
        try{
            
            //güncelledikten sonra inputları alıp yerleştirme
            String name= txtName.getText();
            int aptNo= Integer.parseInt(txtAptNo.getText());
            double rent = Double.parseDouble(txtRent.getText());
            
            
            //Arraylist güncelleme
            Tenant t = manager.getTenants().get(selectedRow);
            t.setName(name);
            t.setAptNo(aptNo);
            t.setRent(rent);
            
            //tablo güncelleme
            dtm.setValueAt(name, selectedRow, 0);
            dtm.setValueAt(aptNo, selectedRow, 1);
            dtm.setValueAt(rent, selectedRow, 2);
        
            
            txtName.setText("");
            txtAptNo.setText("");
            txtRent.setText("");
            
            //tablodan seçilen satırı temizler
            jTable1.clearSelection();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Invalid input!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        txtName.setText(dtm.getValueAt(selectedRow, 0).toString());
        txtAptNo.setText(dtm.getValueAt(selectedRow, 1).toString());
        txtRent.setText(dtm.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAptNo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRent;
    // End of variables declaration//GEN-END:variables
}
